# -*- coding: utf-8 -*-
"""Recruit restaurant ensemble0.53298.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19T-tfgGGsGq_m15gU-rSaiBHXLXq4hRI
"""

import pandas as pd
import numpy as np

preds_cat=pd.read_csv('submission_cat0.53795.csv', usecols=['visitors'])
preds_xgb=pd.read_csv('submission_XGB0.53773.csv',usecols=['visitors'])
preds_pytorch=pd.read_csv('submission_PyTorch0.56299.csv',usecols=['visitors'])
preds_lgbm=pd.read_csv('submission_lgbm0.53397.csv',usecols=['visitors'])

lgbm_coef=0.8
cat_coef=0.15
xgb_coef=0.0
pytorch_coef=0.05

ensemble_preds=(pytorch_coef*preds_pytorch)+(xgb_coef*preds_xgb)+(cat_coef*preds_cat)+(lgbm_coef*preds_lgbm)

submission=pd.read_csv('sample_submission.csv')

submission['visitors']=ensemble_preds

submission.to_csv('submission.csv', index=False, float_format='%.3f')

from google.colab import files

files.download('submission.csv')