# -*- coding: utf-8 -*-
"""Recruit Restaurant Visitor Forecasting_lgbm_0.53397.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hxhSEIDY95MsdiWeGr7ftDecEHPo1wL6
"""

import pandas as pd
import numpy as np
from sklearn.metrics import mean_squared_error as mse
import random
from lightgbm import LGBMRegressor
from sklearn.model_selection import KFold,train_test_split

import gc
import warnings
warnings.filterwarnings('ignore')

def RMSLE(y_pred, y_test):
    return np.sqrt(mse(y_test,y_pred))

def seed_everything(seed=0):
    random.seed(seed)
    np.random.seed(seed)

train=pd.read_csv('Recruit_Restaurant_train.csv')
test=pd.read_csv('Recruit_Restaurant_test.csv')

train.drop(['air_store_id','visit_date','latitude','longitude'], axis=1, inplace=True)
test.drop(['air_store_id','visit_date','latitude','longitude'], axis=1, inplace=True)

X=train.drop('visitors', axis=1)
y=train['visitors']
X_test=test

cat_cols=[col for col in X.columns if X[col].dtype in ['object', 'category'] ]
cat_cols

from sklearn.preprocessing import LabelEncoder

for f in cat_cols:
        lbl = LabelEncoder()
        lbl.fit(list(X[f].values) + list(X_test[f].values))
        X[f] = lbl.transform(list(X[f].values))
        X_test[f] = lbl.transform(list(X_test[f].values))

#for col in cat_cols:
 # train[col]=train[col].astype('category')
 # test[col]=test[col].astype('category')

SEED=2022
seed_everything(SEED)

params = {
    "n_estimators": 5000,
    "boosting_type": "gbdt",
    "num_leaves": 1280,
    "max_depth":-1,
    "learning_rate": 0.01,
    "reg_lambda": 2,
    "colsample_bytree":0.85
    }

NFOLDS=5
seed_range=3
kf=KFold(n_splits=NFOLDS)

preds_seed=np.zeros((X_test.shape[0],seed_range))
val_preds_seed=np.zeros((X.shape[0],seed_range))

for i, s in enumerate(range(SEED, SEED+seed_range)):
  print('SEED:', s)
  preds = np.zeros((X_test.shape[0], NFOLDS))
  val_preds=np.zeros(X.shape[0])
  seed_everything(s)
  params['seed'] = s
  
  for j, (train_idx, test_idx) in enumerate(kf.split(X)):
    fold = j + 1
    print('Fold:',fold)

    kf_X_train=X.iloc[train_idx]
    kf_y_train=y.iloc[train_idx]
    
    kf_X_test=X.iloc[test_idx]
    kf_y_test=y.iloc[test_idx]

    regressor=LGBMRegressor(**params)
    regressor.fit(kf_X_train,kf_y_train, eval_set=(kf_X_test,kf_y_test), eval_metric='rmse',
                early_stopping_rounds=500,verbose=100)
                #categorical_feature = cat_cols
    val_preds[test_idx]+= regressor.predict(X.iloc[test_idx])
    preds[:, j] = regressor.predict(X_test) 
  
  preds=np.mean(preds, axis=1)
  preds_seed[:,i]=preds
  val_preds_seed[:,i]=val_preds

y_pred=np.expm1(np.mean(preds_seed, axis=1))

y_pred.min()

np.save('pred_lgbm.npy', y_pred)

val_preds_final=np.mean(val_preds_seed,axis=1)

RMSLE(val_preds_final, y)

"""**Submission**"""

submission=pd.read_csv('sample_submission.csv')

submission['visitors']=y_pred

submission.to_csv('submission_lgbm.csv', index=False, float_format='%.3f')

from google.colab import files

files.download('submission_lgbm.csv')